defaults: &defaults
  # working_directory: ~/code
  docker:
    - image: circleci/node:9
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
        JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

restore_cache: &restore_cache
  restore_cache:
    keys:
      - code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}

save_cache: &save_cache
  save_cache:
      key: code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
      paths:
        - node_modules

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm run eslint
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm test
      - run: npx codecov

  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - run:
          name: NPM Access
          command: echo "//registry.npmjs.org/:_authToken=$NPM_WRITE_TOKEN" >> ~/.npmrc
      - run: git config --global user.email "circle@dontemailme.com" && git config user.name "CircleCI"
      - run: node scripts/check-package-version.js
      - run: npm publish

workflows:
  version: 2
  all:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build

      - publish:
          filters:
            branches:
              only: master
          requires:
            - build
            - lint
            - test
